server:
  port: 8009
spring:
  redis:
    host: 43.143.201.120
    port: 6379
    password: ajksdhiuwqhuaasd
    timeout: 30000
  profiles:
    active: dev
  application:
    name: service-acl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_school?serverTimezone=GMT%2B8
    username: root
    password: Zzhzzhzzh1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #逻辑删除字段
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations:
    - classpath:com/peels/ServiceAcl/mapper/xml/*.xml


feign:
  #使用连接池代替URLConnection
  httpclient:
    enabled: true
    max-connections-per-route: 50
    max-connections: 200
  #开启熔断
  hystrix:
    enabled: true
