server:
  port: 8160
spring:
  application:
    name: service-ucenter
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_school?serverTimezone=GMT%2B8
    username: root
    password: Zzhzzhzzh1
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  redis:
    host: 43.143.201.120
    port: 6379
    password: ajksdhiuwqhuaasd
    timeout: 30000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #逻辑删除字段
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations:
    - classpath:com/peels/ucenterService/mapper/xml/*.xml
wx:
  open:
    # 微信开放平台 appid
    appid: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    appsecret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url（guli.shop需要在微信开放平台配置）
    redirecturl: http://localhost:8160/api/ucenter/wx/callback
#redirect_url 要改配置文件properties里面的,http://localhost:8160/+你的controller里面的地址，要这个callback指的是你的方法地址，你可以先看下一集会明白一点
