server:
  port: 8005
spring:
  application:
    name: service-msm
  redis:
    host: 43.143.201.120
    port: 6379
    password: ajksdhiuwqhuaasd
    timeout: 30000
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
